/**
 * Módulo de Normalización de Nombres de Equipos de Fútbol
 * Mapea variaciones, alias y apodos hacia nombres estandarizados
 */

function stripAccents(str: string): string {
  return str
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();
}

const ALIAS_MAP: Record<string, string> = {
  // Liga MX
  'america': 'america',
  'club america': 'america',
  'aguilas': 'america',
  'aguilas del america': 'america',
  'chivas': 'guadalajara',
  'chivas guadalajara': 'guadalajara',
  'guadalajara': 'guadalajara',
  'cd guadalajara': 'guadalajara',
  'rebaño': 'guadalajara',
  'rebaño sagrado': 'guadalajara',
  'cruz azul': 'cruz azul',
  'la maquina': 'cruz azul',
  'maquina celeste': 'cruz azul',
  'pumas': 'pumas',
  'pumas unam': 'pumas',
  'unam': 'pumas',
  'universidad nacional': 'pumas',
  'tigres': 'tigres',
  'tigres uanl': 'tigres',
  'uanl': 'tigres',
  'monterrey': 'monterrey',
  'rayados': 'monterrey',
  'rayados de monterrey': 'monterrey',
  'cf monterrey': 'monterrey',
  'toluca': 'toluca',
  'diablos': 'toluca',
  'diablos rojos': 'toluca',
  'deportivo toluca': 'toluca',
  'pachuca': 'pachuca',
  'tuzos': 'pachuca',
  'tuzos del pachuca': 'pachuca',
  'cf pachuca': 'pachuca',
  'atlas': 'atlas',
  'rojinegros': 'atlas',
  'zorros': 'atlas',
  'atlas fc': 'atlas',
  'santos': 'santos',
  'santos laguna': 'santos',
  'club santos': 'santos',
  'guerreros': 'santos',
  'queretaro': 'queretaro',
  'gallos': 'queretaro',
  'gallos blancos': 'queretaro',
  'queretaro fc': 'queretaro',
  'puebla': 'puebla',
  'camoteros': 'puebla',
  'la franja': 'puebla',
  'club puebla': 'puebla',
  'juarez': 'juarez',
  'juarez fc': 'juarez',
  'fc juarez': 'juarez',
  'bravos': 'juarez',
  'bravos de juarez': 'juarez',
  'san luis': 'san luis',
  'atletico san luis': 'san luis',
  'atletico de san luis': 'san luis',
  'atl san luis': 'san luis',
  'atl. san luis': 'san luis',
  'necaxa': 'necaxa',
  'rayos': 'necaxa',
  'rayos del necaxa': 'necaxa',
  'club necaxa': 'necaxa',
  'leon': 'leon',
  'club leon': 'leon',
  'fieras': 'leon',
  'panzas verdes': 'leon',
  'mazatlan': 'mazatlan',
  'mazatlan fc': 'mazatlan',
  'cañoneros': 'mazatlan',
  'tijuana': 'tijuana',
  'xolos': 'tijuana',
  'xolos de tijuana': 'tijuana',
  'club tijuana': 'tijuana',
  'atlante': 'atlante',
  'atlante fc': 'atlante',
  'potros': 'atlante',

  // España (LaLiga)
  'barcelona': 'barcelona',
  'fc barcelona': 'barcelona',
  'barca': 'barcelona',
  'real madrid': 'real madrid',
  'real madrid cf': 'real madrid',
  'madrid': 'real madrid',
  'merengues': 'real madrid',
  'atletico madrid': 'atletico madrid',
  'atletico de madrid': 'atletico madrid',
  'atletico': 'atletico madrid',
  'colchoneros': 'atletico madrid',
  'atm': 'atletico madrid',
  'sevilla': 'sevilla',
  'sevilla fc': 'sevilla',
  'celta': 'celta',
  'celta de vigo': 'celta',
  'celta vigo': 'celta',
  'athletic': 'athletic',
  'athletic club': 'athletic',
  'athletic bilbao': 'athletic',
  'real betis': 'betis',
  'betis': 'betis',
  'balompie': 'betis',
  'villarreal': 'villarreal',
  'villarreal cf': 'villarreal',
  'valencia': 'valencia',
  'valencia cf': 'valencia',
  'real sociedad': 'real sociedad',
  'la real': 'real sociedad',
  'sociedad': 'real sociedad',
  'osasuna': 'osasuna',
  'ca osasuna': 'osasuna',
  'alaves': 'alaves',
  'deportivo alaves': 'alaves',
  'espanyol': 'espanyol',
  'rcd espanyol': 'espanyol',
  'getafe': 'getafe',
  'getafe cf': 'getafe',
  'rayo': 'rayo vallecano',
  'rayo vallecano': 'rayo vallecano',
  'mallorca': 'mallorca',
  'rcd mallorca': 'mallorca',
  'girona': 'girona',
  'girona fc': 'girona',
  'las palmas': 'las palmas',
  'ud las palmas': 'las palmas',
  'leganes': 'leganes',
  'cd leganes': 'leganes',
  'valladolid': 'valladolid',
  'real valladolid': 'valladolid',

  // Inglaterra (Premier League)
  'arsenal': 'arsenal',
  'arsenal fc': 'arsenal',
  'gunners': 'arsenal',
  'aston villa': 'aston villa',
  'aston villa fc': 'aston villa',
  'villa': 'aston villa',
  'liverpool': 'liverpool',
  'liverpool fc': 'liverpool',
  'reds': 'liverpool',
  'manchester city': 'manchester city',
  'man city': 'manchester city',
  'mancity': 'manchester city',
  'citizens': 'manchester city',
  'manchester united': 'manchester united',
  'man united': 'manchester united',
  'man utd': 'manchester united',
  'red devils': 'manchester united',
  'chelsea': 'chelsea',
  'chelsea fc': 'chelsea',
  'blues': 'chelsea',
  'tottenham': 'tottenham',
  'tottenham hotspur': 'tottenham',
  'spurs': 'tottenham',
  'newcastle': 'newcastle',
  'newcastle united': 'newcastle',
  'brighton': 'brighton',
  'brighton and hove albion': 'brighton',
  'brentford': 'brentford',
  'crystal palace': 'crystal palace',
  'everton': 'everton',
  'fulham': 'fulham',
  'bournemouth': 'bournemouth',
  'nottingham forest': 'nottingham',
  'nottingham': 'nottingham',
  'west ham': 'west ham',
  'west ham united': 'west ham',
  'wolves': 'wolverhampton',
  'wolverhampton': 'wolverhampton',
  'wolverhampton wanderers': 'wolverhampton',

  // Italia (Serie A)
  'roma': 'roma',
  'as roma': 'roma',
  'inter': 'inter',
  'inter milan': 'inter',
  'internazionale': 'inter',
  'inter milano': 'inter',
  'milan': 'milan',
  'ac milan': 'milan',
  'rossoneri': 'milan',
  'juventus': 'juventus',
  'juve': 'juventus',
  'napoli': 'napoli',
  'ssc napoli': 'napoli',
  'lazio': 'lazio',
  'ss lazio': 'lazio',
  'atalanta': 'atalanta',
  'atalanta bc': 'atalanta',
  'fiorentina': 'fiorentina',
  'bologna': 'bologna',
  'como': 'como',
  'como 1907': 'como',
  'torino': 'torino',
  'genoa': 'genoa',
  'udinese': 'udinese',
  'cagliari': 'cagliari',
  'parma': 'parma',
  'monza': 'monza',
  'lecce': 'lecce',
  'venezia': 'venezia',

  // Otras Ligas Europeas y Champions League
  'bayern': 'bayern munich',
  'bayern munich': 'bayern munich',
  'bayern munchen': 'bayern munich',
  'fc bayern': 'bayern munich',
  'dortmund': 'borussia dortmund',
  'borussia dortmund': 'borussia dortmund',
  'bvb': 'borussia dortmund',
  'leverkusen': 'bayer leverkusen',
  'bayer leverkusen': 'bayer leverkusen',
  'bayer 04': 'bayer leverkusen',
  'leipzig': 'rb leipzig',
  'rb leipzig': 'rb leipzig',
  'stuttgart': 'vfb stuttgart',
  'vfb stuttgart': 'vfb stuttgart',
  'psg': 'paris saint germain',
  'paris saint germain': 'paris saint germain',
  'paris sg': 'paris saint germain',
  'paris': 'paris saint germain',
  'lille': 'lille',
  'losc lille': 'lille',
  'monaco': 'monaco',
  'as monaco': 'monaco',
  'marseille': 'marseille',
  'om': 'marseille',
  'sporting': 'sporting lisbon',
  'sporting lisboa': 'sporting lisbon',
  'sporting cp': 'sporting lisbon',
  'sporting lisbon': 'sporting lisbon',
  'porto': 'porto',
  'fc porto': 'porto',
  'benfica': 'benfica',
  'sl benfica': 'benfica',
  'psv': 'psv eindhoven',
  'psv eindhoven': 'psv eindhoven',
  'feyenoord': 'feyenoord',
  'ajax': 'ajax',
  'club brugge': 'club brugge',
  'galatasaray': 'galatasaray',
  'fenerbahce': 'fenerbahce',
  
  // América / MLS
  'inter miami': 'inter miami',
  'miami': 'inter miami',
  'la galaxy': 'la galaxy',
  'galaxy': 'la galaxy',
  'lafc': 'los angeles fc',
  'los angeles fc': 'los angeles fc',
  'boca': 'boca juniors',
  'boca juniors': 'boca juniors',
  'river': 'river plate',
  'river plate': 'river plate'
};

export function getCanonicalTeamKey(name: string): string {
  const clean = stripAccents(name);
  if (ALIAS_MAP[clean]) return ALIAS_MAP[clean];
  
  // Buscar si alguna palabra clave coincide
  for (const [alias, canonical] of Object.entries(ALIAS_MAP)) {
    if (clean.includes(alias) || alias.includes(clean)) {
      return canonical;
    }
  }
  return clean;
}

export function matchTeamNames(nameA: string, nameB: string): boolean {
  if (!nameA || !nameB) return false;
  const keyA = getCanonicalTeamKey(nameA);
  const keyB = getCanonicalTeamKey(nameB);
  return keyA === keyB || keyA.includes(keyB) || keyB.includes(keyA);
}
